# Generated by Django 4.1.3 on 2022-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], max_length=10)),
                ('present_simple', models.CharField(max_length=32)),
                ('simple_past', models.CharField(max_length=32)),
                ('past_participle', models.CharField(max_length=32)),
            ],
        ),
    ]
