# Generated by Django 4.1.3 on 2022-11-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='highlighted',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='present_simple',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
