# Generated by Django 4.1.3 on 2022-11-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_verb_highlighted_alter_verb_present_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='highlighted',
            field=models.TextField(),
        ),
    ]
