# Generated by Django 4.1.3 on 2022-11-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_verb_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb',
            name='highlighted',
        ),
    ]
